const W=720,H=1280;
const SAVE_KEY='misa-complete-v2';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const today=()=>new Date().toISOString().slice(0,10);
const DEFAULT={hunger:82,happiness:86,energy:78,cleanliness:88,love:72,coins:100,xp:0,level:1,last:Date.now(),dailyDate:'',dailyClaimed:false,highScore:0,missions:{feed:0,love:0,play:0,clean:0},dailyMissions:{feed:0,love:0,play:0,clean:0},achievements:[],owned:[],equipped:{hat:'',toy:''},room:'home'};
let state;
function load(){try{const r=JSON.parse(localStorage.getItem(SAVE_KEY));state={...DEFAULT,...r,missions:{...DEFAULT.missions,...(r?.missions||{})},dailyMissions:{...DEFAULT.dailyMissions,...(r?.dailyMissions||{})},equipped:{...DEFAULT.equipped,...(r?.equipped||{})},owned:Array.isArray(r?.owned)?r.owned:[],achievements:Array.isArray(r?.achievements)?r.achievements:[]};}catch{state=structuredClone(DEFAULT)}}
function save(){state.last=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));}
function awayDecay(){const mins=Math.max(0,(Date.now()-state.last)/60000);const ticks=Math.min(720,Math.floor(mins/10));if(!ticks)return;state.hunger=clamp(state.hunger-ticks*.42);state.happiness=clamp(state.happiness-ticks*.28);state.energy=clamp(state.energy-ticks*.16);state.cleanliness=clamp(state.cleanliness-ticks*.22);state.love=clamp(state.love-ticks*.10);save();}
load();awayDecay();
const frames=Array.from({length:8},(_,i)=>`misa${i+1}`);
const SHOP=[
{id:'hat_blue',name:'Mavi Şapka',icon:'🎩',price:70,type:'hat'},
{id:'hat_crown',name:'Mini Taç',icon:'👑',price:120,type:'hat'},
{id:'hat_party',name:'Parti Şapkası',icon:'🥳',price:90,type:'hat'},
{id:'toy_ball',name:'Top',icon:'⚽',price:60,type:'toy'},
{id:'toy_mouse',name:'Oyuncak Fare',icon:'🐭',price:80,type:'toy'},
{id:'toy_star',name:'Yıldız Oyuncak',icon:'⭐',price:100,type:'toy'}];
const ACH=[
['first_feed','İlk Mama',s=>s.missions.feed>=1],['lover','Sevgi Pıtırcığı',s=>s.missions.love>=20],['cleaner','Mis Gibi',s=>s.missions.clean>=10],['gamer','Oyun Arkadaşı',s=>s.missions.play>=10],['rich','Kumbaracı',s=>s.coins>=500],['level5','Büyüdün!',s=>s.level>=5]];
const xpNeed=l=>100+l*35;
function mood(){const avg=(state.hunger+state.happiness+state.energy+state.cleanliness+state.love)/5;if(state.energy<20)return ['😴','Uykulu'];if(state.hunger<20)return ['🤤','Çok Aç'];if(state.cleanliness<20)return ['🫧','Kirli'];if(avg>=82)return ['😍','Çok Mutlu'];if(avg>=65)return ['😊','Mutlu'];if(avg>=45)return ['🙂','İyi'];if(avg>=25)return ['🥺','Keyifsiz'];return ['😿','Üzgün'];}

class HomeScene extends Phaser.Scene{
constructor(){super('HomeScene');this.mode='home';this.busy=false;this.idleTimer=null;this.tapTimes=[];this.overlay=null;this.miniObjects=[];this.room='home';}
preload(){frames.forEach((k,i)=>this.load.image(k,`assets/misa/misa_idle_0${i+1}.png`));['home','kitchen','bath','sleep','play'].forEach(r=>this.load.image('room_'+r,`assets/rooms/${r}.jpg`));}
create(){this.cameras.main.setBackgroundColor('#fff7fb');this.add.rectangle(W/2,H/2,W,H,0xfff7fb);this.drawUI();this.buildRooms();this.drawRoomBackdrop(state.room||'home');this.startIdle();this.refresh();this.setupDaily();this.live=this.time.addEvent({delay:60000,loop:true,callback:()=>this.liveDecay()});}
txt(x,y,t,size,color='#342b3b',style='bold'){return this.add.text(x,y,t,{fontFamily:'Arial',fontSize:size+'px',color,fontStyle:style}).setOrigin(.5)}
box(x,y,w,h,color=0xffffff,alpha=1,stroke=0xeadfeb){const r=this.add.rectangle(x,y,w,h,color,alpha).setOrigin(.5);if(stroke!==null)r.setStrokeStyle(2,stroke,1);return r}
button(x,y,w,h,label,fn,color=0xffffff){const b=this.box(x,y,w,h,color,1);b.setInteractive({useHandCursor:true});this.txt(x,y,label,17,'#4f4554');b.on('pointerdown',()=>fn());return b}
drawUI(){
this.title=this.txt(W/2,36,'🐱  MİŞA',40,'#2e2638');this.subtitle=this.txt(W/2,76,"Mehmet ❤️ Özlem'in küçük dünyası",20,'#776b7e');
this.coinText=this.txt(625,38,'🪙 100',22,'#6b4d18');this.levelText=this.txt(82,38,'Lv. 1',22,'#5b4a75');
this.xpBg=this.box(W/2,110,430,14,0xe9e2eb,1,null);this.xpFill=this.add.graphics();this.xpLabel=this.txt(W/2,110,'XP 0/135',12,'#5d5264');
this.statusPanel=this.box(W/2,285,650,290,0xffffff,.96);this.statusTitle=this.txt(W/2,158,'Durum',19,'#5c5262');
this.bars={};[['🍗','Açlık','hunger'],['😊','Mutluluk','happiness'],['⚡','Enerji','energy'],['🧼','Temizlik','cleanliness'],['❤️','Sevgi','love']].forEach((s,i)=>{const y=205+i*43;this.txt(60,y,s[0]+' '+s[1],17,'#5c5262').setOrigin(0,.5);this.bars[s[2]]={y,bg:this.add.graphics(),fill:this.add.graphics(),label:this.txt(570,y,'0%',17,'#675b69').setOrigin(1,.5)};});
this.moodText=this.txt(W/2,430,'😊 Mutlu',18,'#6b5b70');this.messageBox=this.box(W/2,486,560,58,0xffffff,.98);this.message=this.txt(W/2,486,'Mişa seni bekliyor ❤️',19,'#544858');
this.roomLabel=this.txt(W/2,535,'🏠 Oda',18,'#765d87');
this.petZone=this.add.rectangle(W/2,805,620,330,0xffffff,0).setDepth(1).setInteractive();this.misa=this.add.image(W/2,805,'misa1').setOrigin(.5).setScale(.78).setDepth(5).setInteractive({useHandCursor:true});this.misaShadow=this.add.ellipse(W/2,935,220,38,0x6b566b,.16).setDepth(4);this.misa.on('pointerdown',p=>this.petTap(p));this.misa.on('pointermove',p=>{if(p.isDown)this.petStroke(p);});
this.accessoryHat=this.txt(W/2,575,'',48).setDepth(8);this.accessoryToy=this.txt(510,880,'',42).setDepth(8);
[['🍖','Besle','feed'],['❤️','Sev','love'],['🎮','Oyna','play'],['🧼','Yıka','clean'],['💤','Uyu','sleep']].forEach((a,i)=>{const x=80+i*140,y=1030,b=this.box(x,y,122,92,0xffffff,1).setInteractive();this.txt(x,y-15,a[0],30);this.txt(x,y+25,a[1],16,'#4f4554');b.on('pointerdown',()=>this.action(a[2]));});
this.button(40,1150,115,58,'🎤 Konuş',()=>this.talk());this.button(165,1150,125,58,'🎮 Oyunlar',()=>this.openGames());this.button(300,1150,125,58,'🛍️ Mağaza',()=>this.openShop());this.button(435,1150,125,58,'📋 Görevler',()=>this.openMissions());this.button(570,1150,110,58,'🎁 Ödül',()=>this.claimDaily(),0xfff5df);this.resetBtn=this.button(W/2,1220,170,38,'Sıfırla',()=>this.reset());
}
buildRooms(){this.roomButtons=[['🏠 Oda','home',85],['🍖 Mutfak','kitchen',225],['🛁 Banyo','bath',365],['🛏️ Uyku','sleep',505],['🎮 Oyun','play',645]];this.roomButtons.forEach(([label,r,x])=>{const b=this.box(x,600,120,42,0xffffff,1,0xe5dce8).setDepth(6).setInteractive();this.txt(x,600,label,14,'#5b4d61').setDepth(7);b.on('pointerdown',()=>this.changeRoom(r));});}
changeRoom(r){if(this.mode!=='home'||this.busy)return;this.room=r;state.room=r;save();const names={home:'🏠 Oda',kitchen:'🍖 Mutfak',bath:'🛁 Banyo',sleep:'🛏️ Uyku Alanı',play:'🎮 Oyun Alanı'};this.roomLabel.setText(names[r]);this.setMsg(names[r]+' açıldı.');const pos={home:[360,815],kitchen:[395,820],bath:[360,825],sleep:[410,835],play:[330,825]};const [px,py]=pos[r]||pos.home;this.tweens.add({targets:[this.misa,this.misaShadow],x:px,duration:260,ease:'Sine.easeInOut'});this.tweens.add({targets:this.misa,y:py,duration:260,ease:'Sine.easeInOut'});this.tweens.add({targets:this.misaShadow,y:py+130,duration:260,ease:'Sine.easeInOut'});if(r==='sleep')this.animate('sleep');else if(r==='kitchen')this.animate('eat');else if(r==='bath')this.animate('clean');else if(r==='play')this.animate('play');else this.startIdle();this.drawRoomBackdrop(r);}
drawRoomBackdrop(r){if(this.roomDecor)this.roomDecor.destroy();this.roomDecor=this.add.container(0,0).setDepth(2);const img=this.add.image(W/2,805,'room_'+r).setDisplaySize(620,310).setAlpha(1);this.roomDecor.add(img);this.roomDecor.add(this.add.rectangle(W/2,805,620,310,0xffffff,.05));const labels={home:'🏠 Ana Oda',kitchen:'🍖 Mutfak',bath:'🛁 Banyo',sleep:'🛏️ Uyku Alanı',play:'🎮 Oyun Alanı'};const pill=this.add.rectangle(W/2,650,190,34,0xffffff,.9).setStrokeStyle(2,0xe6d8ea,1).setDepth(3);this.roomDecor.add(pill);this.roomDecor.add(this.txt(W/2,650,labels[r],15,'#5b4d61').setDepth(3));}
redrawBar(k){const o=this.bars[k],v=clamp(state[k]);o.bg.clear();o.fill.clear();o.bg.fillStyle(0xeee8f0,1);o.fill.fillStyle(v<25?0xe58aa8:0xeeb1cd,1);o.bg.fillRoundedRect(105,o.y-9,400,18,9);if(v>0)o.fill.fillRoundedRect(105,o.y-9,400*v/100,18,9);o.label.setText(Math.round(v)+'%');}
refresh(){Object.keys(this.bars).forEach(k=>this.redrawBar(k));this.coinText.setText('🪙 '+state.coins);this.levelText.setText('Lv. '+state.level);const need=xpNeed(state.level);this.xpFill.clear();this.xpFill.fillStyle(0x9f8ad5,1);this.xpFill.fillRoundedRect(W/2-215,103,430*(state.xp/need),14,7);this.xpLabel.setText(`XP ${state.xp}/${need}`);const m=mood();this.moodText.setText(`${m[0]} ${m[1]}`);this.accessoryHat.setText(state.equipped.hat?SHOP.find(x=>x.id===state.equipped.hat)?.icon||'':'');this.accessoryToy.setText(state.equipped.toy?SHOP.find(x=>x.id===state.equipped.toy)?.icon||'':'');}
setMsg(t){this.message.setText(t);this.tweens.add({targets:this.message,scale:1.04,duration:140,yoyo:true});}
gainXP(n){state.xp+=n;let leveled=false;while(state.xp>=xpNeed(state.level)){state.xp-=xpNeed(state.level);state.level++;state.coins+=25;leveled=true;}if(leveled){this.setMsg('🎉 Seviye atladın! +25 🪙');this.sparkle();}this.checkAchievements();}
startIdle(){if(this.mode!=='home'||!this.misa)return;if(this.idleTimer)this.idleTimer.remove();const seq=[1,2,3,4,5,6,7,8,7,6,5,4,3,2];let i=0;this.idleTimer=this.time.addEvent({delay:150,loop:true,callback:()=>{if(this.mode==='home'&&!this.busy)this.misa.setTexture('misa'+seq[i++%seq.length]);}});}
animate(type){if(this.idleTimer)this.idleTimer.remove();const dur={eat:1100,love:1000,play:1300,clean:1200,sleep:1900}[type]||1000;const seq={eat:['misa1','misa3','misa5','misa3','misa1'],love:['misa1','misa4','misa7','misa4','misa1'],play:['misa1','misa6','misa8','misa6','misa1'],clean:['misa1','misa2','misa6','misa2','misa1'],sleep:['misa1','misa7','misa8','misa7','misa8']}[type];let i=0;this.misa.setTexture(seq[0]);this.tweens.add({targets:this.misa,scale:type==='sleep'?.78:.95,duration:dur/2,yoyo:true,ease:'Sine.easeInOut'});this.time.addEvent({delay:dur/(seq.length-1),repeat:seq.length-2,callback:()=>this.misa.setTexture(seq[++i])});}
petTap(p){if(this.mode!=='home'||this.busy)return;const now=Date.now();this.tapTimes=this.tapTimes.filter(t=>now-t<900);this.tapTimes.push(now);const x=p.x,y=p.y;let kind='body';if(y<700)kind='head';else if(y>850)kind='paws';else if(x<300)kind='tail';else kind='belly';const reactions={head:['😽 Mişa mırlıyor!','love'],belly:['😂 Gıdıklandım!','love'],tail:['😾 Kuyruğuma dokunma!','angry'],paws:['🐾 Patisini uzattı!','play'],body:['❤️ Mişa sevgini hissetti!','love']};const [msg,anim]=reactions[kind];state.love=clamp(state.love+4);state.happiness=clamp(state.happiness+3);this.gainXP(2);this.setMsg(msg);this.animate(anim==='angry'?'clean':anim);this.floatIcons(kind==='head'?'❤️':kind==='belly'?'😂':'🐾');if(this.tapTimes.length>=5){this.setMsg('😂 Tamam tamam, çok gıdıklanıyorum!');state.happiness=clamp(state.happiness+8);this.sparkle();this.tapTimes=[];}save();this.refresh();}
petStroke(p){if(!this.strokeAt||Date.now()-this.strokeAt>300){this.strokeAt=Date.now();state.love=clamp(state.love+1);state.happiness=clamp(state.happiness+1);this.refresh();}}
action(type){if(this.busy||this.mode!=='home')return;this.busy=true;let ok=true;if(type==='feed'){state.hunger=clamp(state.hunger+22);state.happiness=clamp(state.happiness+5);state.missions.feed++;state.dailyMissions.feed++;this.gainXP(12);this.setMsg('😋 Mişa karnını doyurdu!');this.animate('eat');}
else if(type==='love'){state.love=clamp(state.love+12);state.happiness=clamp(state.happiness+10);state.missions.love++;state.dailyMissions.love++;this.gainXP(10);this.setMsg('❤️ Mişa mırıldanıyor.');this.animate('love');this.floatIcons('❤️');}
else if(type==='play'){if(state.energy<12){ok=false;this.setMsg('🥱 Mişa çok yorgun. Önce uyut!');}else{state.energy=clamp(state.energy-12);state.happiness=clamp(state.happiness+22);state.love=clamp(state.love+4);state.missions.play++;state.dailyMissions.play++;this.gainXP(16);this.setMsg('🎉 Mişa seninle oynuyor!');this.animate('play');}}
else if(type==='clean'){state.cleanliness=clamp(state.cleanliness+30);state.happiness=clamp(state.happiness+5);state.missions.clean++;state.dailyMissions.clean++;this.gainXP(12);this.setMsg('🫧 Mişa mis gibi oldu!');this.animate('clean');this.floatIcons('🫧');}
else if(type==='sleep'){state.energy=clamp(state.energy+35);state.happiness=clamp(state.happiness+3);this.gainXP(8);this.setMsg('💤 Mişa dinleniyor...');this.animate('sleep');}
if(ok){save();this.refresh();this.time.delayedCall(type==='sleep'?1900:1200,()=>{this.busy=false;this.startIdle();});}else this.busy=false;}
liveDecay(){if(this.mode!=='home'||this.busy)return;state.hunger=clamp(state.hunger-.18);state.happiness=clamp(state.happiness-.12);state.energy=clamp(state.energy-.06);state.cleanliness=clamp(state.cleanliness-.10);state.love=clamp(state.love-.04);save();this.refresh();}
floatIcons(icon){for(let i=0;i<5;i++){const t=this.txt(W/2+(Math.random()*100-50),720,icon,26);this.tweens.add({targets:t,y:t.y-90-Math.random()*50,alpha:0,duration:800,delay:i*60,onComplete:()=>t.destroy()});}}
sparkle(){for(let i=0;i<12;i++){const t=this.txt(W/2+(Math.random()*300-150),760+(Math.random()*180-90),'✨',20);this.tweens.add({targets:t,y:t.y-80,alpha:0,duration:700,delay:i*25,onComplete:()=>t.destroy()});}}
setupDaily(){if(state.dailyDate!==today()){state.dailyDate=today();state.dailyClaimed=false;state.dailyMissions={feed:0,love:0,play:0,clean:0};save();}}
claimDaily(){if(state.dailyClaimed){this.setMsg('🎁 Bugünkü ödülünü zaten aldın.');return;}state.dailyClaimed=true;state.coins+=50;state.happiness=clamp(state.happiness+10);save();this.refresh();this.setMsg('🎁 Günlük ödül: +50 🪙');this.sparkle();}
checkAchievements(){ACH.forEach(a=>{if(!state.achievements.includes(a[0])&&a[2](state)){state.achievements.push(a[0]);state.coins+=40;this.setMsg('🏆 Başarım: '+a[1]+' • +40 🪙');save();}});}
openGames(){const o=this.overlayBase('🎮 Mini Oyunlar');this.addOverlayText(360,215,'Mişa ile oynayarak coin ve XP kazan!',18);this.overlayButton(360,320,500,82,'🎈 Balon Avı',()=>this.startBalloonGame());this.overlayButton(360,425,500,82,'🐟 Balık Yakala',()=>this.startTargetGame('🐟','Balık Yakala'));this.overlayButton(360,530,500,82,'⭐ Yıldız Topla',()=>this.startTargetGame('⭐','Yıldız Topla'));this.addOverlayText(360,680,`🏆 Rekor: ${state.highScore}`,18);}
overlayBase(title){if(this.overlay)this.closeOverlay();this.mode='overlay';if(this.idleTimer)this.idleTimer.remove();const shade=this.add.rectangle(W/2,H/2,W,H,0x2f2738,.92).setDepth(20);const panel=this.box(W/2,650,640,1080,0xfffbfe,1,0xe7dbe8).setDepth(21);const t=this.txt(W/2,150,title,30,'#3e3445').setDepth(22);const close=this.txt(620,150,'✕',28,'#6f5d72').setDepth(22).setInteractive();close.on('pointerdown',()=>this.closeOverlay());this.overlay={shade,panel,t,close,items:[]};return this.overlay;}
addOverlayText(x,y,text,size=18,color='#514657'){const o=this.txt(x,y,text,size,color).setDepth(22);this.overlay.items.push(o);return o}
overlayButton(x,y,w,h,label,fn){const b=this.box(x,y,w,h,0xffffff,1,0xe5dce8).setDepth(22).setInteractive();this.addOverlayText(x,y,label,20);b.on('pointerdown',fn);this.overlay.items.push(b);return b;}
closeOverlay(){if(!this.overlay)return;Object.values(this.overlay).forEach(v=>{if(Array.isArray(v))v.forEach(o=>o.destroy());else if(v?.destroy)v.destroy();});this.overlay=null;this.mode='home';this.startIdle();this.refresh();}
startBalloonGame(){this.closeOverlay();this.mode='mini';this.hideHome(true);this.misa.setVisible(false);this.miniScore=0;this.miniTime=20;this.miniObjects=[];this.miniShade=this.add.rectangle(W/2,H/2,W,H,0x3f3552,.97).setDepth(30);this.miniTitle=this.txt(W/2,150,'🎈 MİŞA BALON AVI',34,'#fff').setDepth(31);this.miniScoreText=this.txt(W/2,220,'Skor: 0',25,'#fff').setDepth(31);this.miniTimeText=this.txt(W/2,260,'20',24,'#fff').setDepth(31);this.miniClose=this.txt(360,1140,'✕ Oyundan çık',19,'#fff').setDepth(31).setInteractive();this.miniClose.on('pointerdown',()=>this.endMini(false));this.spawnBalloon();this.miniTimer=this.time.addEvent({delay:1000,repeat:19,callback:()=>{this.miniTime--;this.miniTimeText.setText(String(this.miniTime));}});this.miniEnd=this.time.delayedCall(20000,()=>this.endMini(true));}
spawnBalloon(){if(this.mode!=='mini')return;const x=70+Math.random()*580,y=380+Math.random()*620;const b=this.add.circle(x,y,40,0xffa9c5).setDepth(32).setInteractive();const e=this.txt(x,y,'🎈',28).setDepth(33);this.miniObjects.push(b,e);b.on('pointerdown',()=>{if(this.mode!=='mini')return;this.miniScore++;this.miniScoreText.setText('Skor: '+this.miniScore);b.destroy();e.destroy();this.spawnBalloon();});this.time.delayedCall(1500,()=>{if(b.active){b.destroy();e.destroy();this.spawnBalloon();}});}
startTargetGame(icon,title){this.closeOverlay();this.mode='mini';this.hideHome(true);this.misa.setVisible(false);this.miniScore=0;this.miniTime=20;this.miniObjects=[];this.miniShade=this.add.rectangle(W/2,H/2,W,H,0x314255,.97).setDepth(30);this.miniTitle=this.txt(W/2,150,'🎯 '+title,34,'#fff').setDepth(31);this.miniScoreText=this.txt(W/2,220,'Skor: 0',25,'#fff').setDepth(31);this.miniTimeText=this.txt(W/2,260,'20',24,'#fff').setDepth(31);this.miniClose=this.txt(360,1140,'✕ Oyundan çık',19,'#fff').setDepth(31).setInteractive();this.miniClose.on('pointerdown',()=>this.endMini(false));this.targetIcon=icon;this.spawnTarget();this.miniTimer=this.time.addEvent({delay:1000,repeat:19,callback:()=>{this.miniTime--;this.miniTimeText.setText(String(this.miniTime));}});this.miniEnd=this.time.delayedCall(20000,()=>this.endMini(true));}
spawnTarget(){if(this.mode!=='mini')return;const x=60+Math.random()*600,y=380+Math.random()*620;const t=this.txt(x,y,this.targetIcon,54).setDepth(32).setInteractive();this.miniObjects.push(t);t.on('pointerdown',()=>{if(this.mode!=='mini')return;this.miniScore++;this.miniScoreText.setText('Skor: '+this.miniScore);t.destroy();this.spawnTarget();});this.time.delayedCall(1300,()=>{if(t.active){t.destroy();this.spawnTarget();}});}
endMini(reward){if(this.mode!=='mini')return;this.time.removeAllEvents();this.miniObjects.forEach(o=>o.destroy());this.miniObjects=[];[this.miniShade,this.miniTitle,this.miniScoreText,this.miniTimeText,this.miniClose].forEach(o=>o?.destroy());if(reward){const coins=Math.min(80,10+this.miniScore*2);state.coins+=coins;state.happiness=clamp(state.happiness+Math.min(25,this.miniScore));state.energy=clamp(state.energy-5);state.missions.play++;state.dailyMissions.play++;this.gainXP(this.miniScore*3);state.highScore=Math.max(state.highScore,this.miniScore);save();this.setMsg(`🏆 Oyun bitti! +${coins} 🪙`);}this.mode='home';this.hideHome(false);this.misa.setVisible(true);this.startIdle();this.refresh();}
hideHome(hide){const names=['title','subtitle','coinText','levelText','xpBg','xpFill','xpLabel','statusPanel','statusTitle','moodText','messageBox','message','petZone','accessoryHat','accessoryToy','resetBtn','roomLabel'];this.children.list.forEach(o=>{if(names.includes(o)||Object.values(this.bars).some(v=>[v.bg,v.fill,v.label].includes(o)))o.setVisible(!hide);});this.roomButtons?.forEach(([,,x])=>{this.children.list.filter(o=>o.x===x&&o.y===600).forEach(o=>o.setVisible(!hide));});}
openShop(){this.overlayBase('🛍️ Mişa Mağazası');this.addOverlayText(360,210,'Coinlerini aksesuarlar için kullan.',18);SHOP.forEach((item,i)=>{const y=295+i*105;const owned=state.owned.includes(item.id);this.addOverlayText(155,y,item.icon,36);this.addOverlayText(310,y,item.name,18);const b=this.box(535,y,150,58,owned?0xe9f5e9:0xffffff,1,0xe5dce8).setDepth(22).setInteractive();this.addOverlayText(535,y,owned?'KUŞAN':`🪙 ${item.price}`,15,owned?'#397044':'#6b4d18');b.on('pointerdown',()=>this.buyOrEquip(item));this.overlay.items.push(b);});}
buyOrEquip(item){if(state.owned.includes(item.id)){state.equipped[item.type]=state.equipped[item.type]===item.id?'':item.id;save();this.refresh();this.openShop();return;}if(state.coins<item.price){this.setMsg('🪙 Yeterli coin yok.');return;}state.coins-=item.price;state.owned.push(item.id);state.equipped[item.type]=item.id;save();this.refresh();this.openShop();}
openMissions(){this.overlayBase('📋 Görevler & Başarımlar');this.addOverlayText(360,215,'Bugünkü görevlerin',20);[['🍖','Besle',state.dailyMissions.feed],['❤️','Sev',state.dailyMissions.love],['🎮','Oyna',state.dailyMissions.play],['🧼','Yıka',state.dailyMissions.clean]].forEach((m,i)=>{this.addOverlayText(170,300+i*65,`${m[0]} ${m[1]}`,18);this.addOverlayText(540,300+i*65,`${m[2]} kez`,18,'#6d5aa8');});this.addOverlayText(360,600,'🏆 Başarımlar',22);ACH.forEach((a,i)=>{const u=state.achievements.includes(a[0]);this.addOverlayText(150,670+i*70,u?'🏆':'🔒',24);this.addOverlayText(230,670+i*70,a[1],18,u?'#4b7a52':'#625767');});}
talk(){if(this.busy||this.mode!=='home')return;const p=['Miyav! 😺','Mehmet, biraz sevgi istiyorum! ❤️','Özlem nerede? 😸','Biraz oyun oynayalım mı? 🎮','Karnım acıkınca haber veririm! 🍖'];const phrase=p[Math.floor(Math.random()*p.length)];this.setMsg('🗣️ Mişa: '+phrase);window.misaSpeak(phrase);this.floatIcons('💬');}
reset(){if(confirm('Mişa’yı ve tüm ilerlemeyi sıfırlamak istediğine emin misin?')){localStorage.removeItem(SAVE_KEY);location.reload();}}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#fff7fb',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH,width:W,height:H},render:{antialias:true,roundPixels:false},input:{activePointers:3},scene:[HomeScene]});
window.misaSpeak=function(text){try{if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='tr-TR';u.rate=.94;u.pitch=1.42;speechSynthesis.speak(u);}}catch(e){}};
